### ISSUE TITLE
Under certain circumstances pre-built boost libraries are considered missing even though present

### ISSUE THREAD

**Issue by ja11sop** [ja11sop/cuppa#26]
For example sometimes I receive this error:

```
BoostLibraryAction(["_cuppa/http_sourceforge.net__projects_boost_files_boost_1.64.0_boost_1_64_0.tar.gz_download/clean/build.c++1z/gcc64/debug/x86_64/lib/libboost_regex.a"], [])
./bjam -j 1 --with-regex toolset=gcc-6 variant=debug    cxxflags="-std=c++1z" define="BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG" link=static --build-dir=./bin.c++1z stage --stagedir=./build.c++1z/gcc64/debug/x86_64 --ignore-site-config
Install file: "_cuppa/http_sourceforge.net__projects_boost_files_boost_1.64.0_boost_1_64_0.tar.gz_download/clean/build.c++1z/gcc64/debug/x86_64/lib/libboost_regex.a" as "_build/sodabread/gcc64/dbg/x86_64/c++1z/working/libboost_regex.a"
scons: *** [_cuppa/http_sourceforge.net__projects_boost_files_boost_1.64.0_boost_1_64_0.tar.gz_download/clean/build.c++1z/gcc64/debug/x86_64/lib/libboost_regex.a] TypeError : 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/lib/scons/SCons/Taskmaster.py", line 248, in execute
    self.targets[0].build()
  File "/usr/lib/scons/SCons/Node/__init__.py", line 739, in build
    self.get_executor()(self, **kw)
TypeError: 'NoneType' object is not callable
scons: building terminated because of errors.
```

**Comment by ja11sop** [comment]
This fix results in internal SCons errors about cyclic dependencies so needs to be revisited
