### ISSUE TITLE
CreateVersion() causes build failure with some git branch arrangements

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#45]
It seems that under some arrangement of git branches, CreateVersion() will throw an exception which causes a build failure. Details to follow shortly

**Comment by feedhandler** [comment]
scons output:
```
scons: Reading SConscript files ...
cuppa: configure: [info] No settings to load, skipping configure
cuppa: version: [info] cuppa: version 0.9.26
cuppa: construct: [info] Running in OFFLINE mode
cuppa: construct: [info] using sconstruct file [SConstruct]
Could not detect the version of libc installed. You might be missing some development libraries!
cuppa: construct: [info] available toolchains are ['gcc48', 'gcc']
cuppa: construct: [info] default profiles are ['devtoolset']
cuppa: construct: [info] default dependencies are ['Core', 'boost', 'date', 'elektron', 'expectedLite', 'json', 'pugixml']
cuppa: construct: [info] Using sub-sconscripts ['./src/SConscript']
cuppa: __init__: [critical] Cuppa terminated by exception [ValueError: need more than 4 values to unpack]
cuppa: __init__: [warn] Use --verbosity=exception (or above) to see the stack
scons: *** need more than 4 values to unpack  Stop.
tim@localhost>
```

**Comment by feedhandler** [comment]
With --verbosity=trace and some extra logging (the ">>>" lines), it shows the error:
```
cuppa: git: get_branch: /home/tim/.local/lib/python2.7/site-packages/cuppa/scms/git.py:62 [trace] Branches (using show) for [/home/tim/repo/ba-darwin] are ['tag: 1.7.0', 'origin/master', 'master']
cuppa: git: get_branch: /home/tim/.local/lib/python2.7/site-packages/cuppa/scms/git.py:72 [trace] Branch (using show) for [/home/tim/repo/ba-darwin] is [master]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>('git@XXXXXXXXX/ba-darwin.git', 'git@XXXXXX/ba-darwin.git', ('master', 'origin/master'), 'ab9ad66')
cuppa: git: get_branch: /home/tim/.local/lib/python2.7/site-packages/cuppa/scms/git.py:62 [trace] Branches (using show) for [/home/tim/repo/ba-darwin] are ['tag: 1.7.0', 'origin/master', 'master']
cuppa: git: get_branch: /home/tim/.local/lib/python2.7/site-packages/cuppa/scms/git.py:72 [trace] Branch (using show) for [/home/tim/repo/ba-darwin] is [master]
cuppa: __init__: log_exception: /home/tim/.local/lib/python2.7/site-packages/cuppa/__init__.py:20 [critical] Cuppa terminated by exception [ValueError: need more than 4 values to unpack]
cuppa: __init__: log_exception: /home/tim/.local/lib/python2.7/site-packages/cuppa/__init__.py:24 [exception] Traceback (most recent call last):
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/__init__.py", line 41, in run
    cuppa.construct.run( sconstruct_path, *args, **kwargs )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/construct.py", line 899, in run
    Construct( *args, **kwargs )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/construct.py", line 512, in __init__
    self.build( cuppa_env )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/construct.py", line 797, in build
    self.call_project_sconscript_files( toolchain, build_env['variant'], build_env['target_arch'], build_env['abi'], build_env['env'], sconscript )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/construct.py", line 886, in call_project_sconscript_files
    exports     = sconscript_exports
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614, in __call__
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551, in SConscript
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256, in _SConscript
    call_stack[-1].globals)
  File "/home/tim/repo/ba-darwin/src/SConscript", line 27, in <module>
    buildAppWithVersion(env, 'showVersion', 'showVersion.cpp', 'version.cpp')
  File "/home/tim/repo/ba-darwin/src/SConscript", line 23, in buildAppWithVersion
    VersionString
  File "/usr/lib/python2.7/site-packages/SCons/Environment.py", line 224, in __call__
    return self.method(*nargs, **kwargs)
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/methods/create_version.py", line 19, in __call__
    create_version_file_builder = env['toolchain'].version_file_builder( env, namespaces, version, location=location, build_id=build_id )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/toolchains/gcc.py", line 343, in version_file_builder
    return CreateVersionFileCpp( env, namespace, version, location, build_id=build_id )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/cpp/create_version_file_cpp.py", line 207, in __init__
    location = cuppa.location.Location( env, location )
  File "/home/tim/.local/lib/python2.7/site-packages/cuppa/location.py", line 479, in __init__
    self._url, self._repository, self._branch, self._remote, self._revision = self.get_info( self._location, self._local_directory, self._full_url )
ValueError: need more than 4 values to unpack

scons: *** need more than 4 values to unpack  Stop.
tim@localhost>
```
In location.py line 479 (ish) it's expecting a 5-tuple from self.get_info
```
        self._url, self._repository, self._branch, self._remote, self._revision = self.get_info( self._location, self._local_directory, self._full_url )
```
But for some reason it's only returning a 4-tuple:
```
('git@XXXXXXXXX/ba-darwin.git', 'git@XXXXXX/ba-darwin.git', ('master', 'origin/master'), 'ab9ad66')
```
It seems that this code works OK in many cases, but for some combinations of branches/tags/remotes/etc it can fail.

**Comment by feedhandler** [comment]
Actually after a bit more investigation it seems like this might be related to (mis)use of RedHat devtoolset in our SConstruct file. I'll close this issue for now as I can't tell for certain that it's a cuppa issue.
